#!/bin/bash

LOCAL="--local"
DOCKER="--docker"
LINEAR="--linear"
CONCURRENT="--concurrent"
BOTH="--both"
TEST="--test-and-show"
SAVE="--test-and-save"

LINEAR_COMMAND="mvn compile exec:java -Plinear"
CONCURRENT_COMMAND="mvn compile exec:java -Pconcurrent"

DOCKER_IMAGE="maven:3.9-eclipse-temurin-21"
LINEAR_DOCKER_COMMAND="docker run -it --rm -v $(pwd):/usr/src/labo1 -w /usr/src/labo1 $DOCKER_IMAGE $LINEAR_COMMAND"
CONCURRENT_DOCKER_COMMAND="docker run -it --rm -v $(pwd):/usr/src/labo1 -w /usr/src/labo1 $DOCKER_IMAGE $CONCURRENT_COMMAND"

usage(){
	echo 
	echo "================================= USAGE ===================================="
	echo
	echo "\"$0 <mode> [target]\""
	echo
	echo "target is optional and can be either --local or --docker"
	echo "if target is left blank, script is run in local"
	echo 
	echo "Mode can be either :"
	echo "	--concurrent		run the concurrent search main "
	echo "	--linear		run the linear search main"
	echo "	--both			run the linear and then the concurrent search mains"
	echo "	--test-and-show		run both the scripts, plot the results with python and show it"
	echo "	--test-and-save		run both the scripts, plot the results with python and save the image"
	echo 
	echo "Dependencies : "
	echo "	- to use local target, maven is required"
	echo "	- to use docker target, docker must be installed"
	echo "	- to use test mode, python≥3.9 with matplotlib must be installed"
	echo
	echo "============================================================================"
	echo
}

show_graphs(){
	filename1=$1
	filename2=$2
	mode=$3
	
	command="python3 grapher.py $filename1 $filename2"
	
	if [[ $mode == $SAVE ]]; then
		echo "INFO running command '$command --save'"
		$command --save 
	else
		echo "INFO running command '$command'"
		$command
	fi
}

if [[ $# -eq 1 && $1 == "--help" ]]; then
	usage
	exit 10
fi

if [[ $# -ne 1 && $# -ne 2 ]]; then
	echo ERROR 
	usage
	exit 11
fi
	
if [[ $# -eq 1 ]]; then
	target=$LOCAL
	mode=$1
else
	mode=$1
	target=$2

fi

if [[ $mode != $LINEAR && $mode != $CONCURRENT && $mode != $BOTH && $mode != $TEST && $mode != $SAVE ]]; then
	echo ERROR invalid mode "$mode"
	usage
	exit 3
fi

if [[ $target != $LOCAL && $target != $DOCKER ]]; then
	echo ERROR invalid target "$target"
	usage
	exit 4
fi

if [[ $mode == $TEST && $target == $DOCKER ]]; then
	echo "ERROR cannot use test mode with docker (only because im too lazy, sry)"
	exit 20
fi

if [[ $mode == $SAVE && $target == $DOCKER ]]; then
	echo "ERROR cannot use test mode with docker (only because im too lazy, sry)"
	exit 21
fi


if [[ $target == $LOCAL ]]; then
	mvn -v > /dev/null || (echo "ERROR maven is not installed"; exit 1)
	
	if [[ $mode == $LINEAR || $mode == $BOTH || $mode == $TEST || $mode == $SAVE ]]; then
		echo INFO running in linear mode on local
		linear_result_fn=$($LINEAR_COMMAND | tee output.log | grep 'Results saved in' | awk '{print $4}')
		echo "INFO done, results is stored in $linear_result_fn"
    fi
	if [[ $mode == $CONCURRENT || $mode == $BOTH || $mode == $TEST || $mode == $SAVE ]]; then
		echo INFO running in concurrent mode on local
		concurrent_result_fn=$($CONCURRENT_COMMAND | tee output.log | grep 'Results saved in' | awk '{print $4}')
		echo "INFO done, results is stored in $concurrent_result_fn"
	fi
	
	if [[ $mode == $TEST || $mode == $SAVE ]]; then
		echo "INFO showing graphs"
		show_graphs $concurrent_result_fn $linear_result_fn $mode
		echo INFO done
	fi
		
	
else
	docker -v > /dev/null || (echo "ERROR docker is not installed"; exit 2) 

	if [[ $mode == $LINEAR || $mode == $BOTH ]]; then
		echo INFO running in linear mode on docker
		$LINEAR_DOCKER_COMMAND
	fi
	if [[ $mode == $CONCURRENT || $mode == $BOTH ]]; then
		echo INFO running in concurrent mode on docker
		$CONCURRENT_DOCKER_COMMAND
	fi
fi

